
- name: Run docker mariadb container
  docker_container:
    name: "mariadb"
    image: "mariadb:10.4.11-bionic"
    restart_policy: always
    env:
      MYSQL_DATABASE: '{{ database_name }}'
      MYSQL_USER: '{{ database_user }}'
      MYSQL_PASSWORD: '{{ database_password }}'
      MYSQL_ROOT_PASSWORD: '{{ database_password }}'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    state: started
  tags:
    - mariadb
